---
- name: Retrieve secrets from Vault
  hosts: localhost
  gather_facts: no
  vars:
    vault_addr: "{{ lookup('env', 'VAULT_ADDR') }}"
    vault_namespace: "{{ lookup('env', 'VAULT_NAMESPACE') }}"
  tasks:
    - name: Read Vault token
      ansible.builtin.slurp:
        src: /root/.vault/root_token
      register: vault_token_b64
      
    - name: Decode token
      set_fact:
        vault_token: "{{ vault_token_b64.content | b64decode }}"
      no_log: true
      
    - name: Get database credentials
      ansible.builtin.uri:
        url: "{{ vault_addr }}/v1/secret/data/app/database"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_token }}"
          X-Vault-Namespace: "{{ vault_namespace }}"
        status_code: 200
      register: db_creds
      no_log: true
      
    - name: Get API key
      ansible.builtin.uri:
        url: "{{ vault_addr }}/v1/secret/data/app/api"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_token }}"
          X-Vault-Namespace: "{{ vault_namespace }}"
        status_code: 200
      register: api_key
      no_log: true
      
    - name: Set facts for other plays
      set_fact:
        db_username: "{{ db_creds.json.data.data.username }}"
        db_password: "{{ db_creds.json.data.data.password }}"
        api_key: "{{ api_key.json.data.data.api_key }}"
        
    - name: Display retrieved secrets
      debug:
        msg: |
          Database Username: {{ db_username }}
          Database Password: {{ db_password | truncate(3, true, '...') }}
          API Key: {{ api_key | truncate(3, true, '...') }}