---
- name: Rotate secrets in Vault
  hosts: localhost
  gather_facts: no
  vars:
    vault_addr: "{{ lookup('env', 'VAULT_ADDR') }}"
    new_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation length=16') }}"
    new_api_key: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=24') }}"
  tasks:
    - name: Read Vault token
      ansible.builtin.slurp:
        src: /root/.vault/root_token
      register: vault_token_b64
      
    - name: Decode token
      set_fact:
        vault_token: "{{ vault_token_b64.content | b64decode }}"
      no_log: true
      
    - name: Get current database credentials
      ansible.builtin.uri:
        url: "{{ vault_addr }}/v1/secret/data/app/database"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_token }}"
        status_code: 200
      register: current_db_creds
      
    - name: Update database password
      ansible.builtin.uri:
        url: "{{ vault_addr }}/v1/secret/data/app/database"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_token }}"
        body_format: json
        body:
          data:
            username: "{{ current_db_creds.json.data.data.username }}"
            password: "{{ new_password }}"
        status_code: 200
      no_log: true
      
    - name: Update API key
      ansible.builtin.uri:
        url: "{{ vault_addr }}/v1/secret/data/app/api"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_token }}"
        body_format: json
        body:
          data:
            api_key: "{{ new_api_key }}"
        status_code: 200
      no_log: true
      
    - name: Get updated database credentials
      ansible.builtin.uri:
        url: "{{ vault_addr }}/v1/secret/data/app/database"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_token }}"
        status_code: 200
      register: new_db_creds
      
    - name: Get updated API key
      ansible.builtin.uri:
        url: "{{ vault_addr }}/v1/secret/data/app/api"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_token }}"
        status_code: 200
      register: new_api_key
      
    - name: Update systemd service file with new credentials
      ansible.builtin.template:
        src: /opt/ansible-demo/playbooks/templates/demo-app.service.j2
        dest: /etc/systemd/system/demo-app.service
        mode: '0644'
      vars:
        db_username: "{{ new_db_creds.json.data.data.username }}"
        db_password: "{{ new_db_creds.json.data.data.password }}"
        api_key: "{{ new_api_key.json.data.data.api_key }}"
      
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes
        
    - name: Restart the application
      ansible.builtin.systemd:
        name: demo-app
        state: restarted
        
    - name: Confirm secrets rotation
      debug:
        msg: |
          Secrets have been successfully rotated in Vault.
          New DB Password: {{ new_db_creds.json.data.data.password | truncate(3, true, '...') }}
          New API Key: {{ new_api_key.json.data.data.api_key | truncate(3, true, '...') }}