---
- name: Authenticate to Vault using AppRole
  hosts: localhost
  gather_facts: no
  vars:
    vault_addr: "{{ lookup('env', 'VAULT_ADDR') }}"
    vault_namespace: "{{ lookup('env', 'VAULT_NAMESPACE') }}"
  tasks:
    - name: Read AppRole credentials
      ansible.builtin.shell: |
        grep role_id /root/.vault/approle | cut -d= -f2
      register: role_id
      no_log: true
      
    - name: Read AppRole secret ID
      ansible.builtin.shell: |
        grep secret_id /root/.vault/approle | cut -d= -f2
      register: secret_id
      no_log: true

    - name: Authenticate to Vault using AppRole
      community.hashi_vault.vault_login:
        url: "{{ vault_addr }}"
        auth_method: approle
        role_id: "{{ role_id.stdout }}"
        secret_id: "{{ secret_id.stdout }}"
        namespace: "{{ vault_namespace }}"
      register: vault_auth
      no_log: true

    - name: Save Vault token
      ansible.builtin.copy:
        content: "{{ vault_auth.login.auth.client_token }}"
        dest: /root/.vault/root_token
        mode: '0600'
      no_log: true
      
    - name: Confirm authentication
      debug:
        msg: "Successfully authenticated to Vault. Token expires in {{ vault_auth.login.auth.lease_duration | default(3600) }} seconds."